# drivers/sharp/bwpm/Makefile  (Makefile for BT/WiFi Power Management)
#
# Copyright (C) 2009 SHARP CORPORATION
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

EXTRA_CFLAGS += -DBWPM_INI_FM=0
EXTRA_CFLAGS += -DBWPM_INI_BT=1
EXTRA_CFLAGS += -DBWPM_INI_WL=0
EXTRA_CFLAGS += -DBWPM_DEBUG

obj-y	+= bwpm.o
