#
# Copyright (C) 2009 SHARP CORPORATION
# Copyright (C) 2009 Yamaha CORPORATION
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#


#
# Makefile for the linux kernel.
#

obj-y := ae2drv.o
